version: '3.8'

services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ingestion_db

  migration:
    image: mongo:7
    depends_on:
      - mongodb
    volumes:
      - "./migration.js:/migration.js"
    command: |
      bash -c '
        until mongosh --host mongodb:27017 --eval "db.runCommand({ping: 1})" --quiet; do
          sleep 2
        done
        mongosh --host mongodb:27017 ingestion_db /migration.js
      '

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "9000:9000"
    environment:
      SERVICES: s3,sqs,cloudformation,ecs,dynamodb,cloudwatch,ec2,iam,logs,application-autoscaling
      DEBUG: 1
      START_WEB: 1
      PORT_WEB_UI: 9000
    volumes:
      - "./localstack:/etc/localstack/init/ready.d"