version = 0.1
[default.deploy.parameters]
stack_name = "data_ingestion"
resolve_s3 = true
s3_prefix = "data_ingestion"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "DatabaseType=\"mongodb\" MongoDBURI=\"mongodb://localhost:27017\" MongoDBDatabase=\"ingestion_db\" DynamoDBConfigTable=\"ingestion_config\" ImageUri=\"test\" BucketName=\"data-ingestion-bucket\""
image_repositories = []
